services:
  app:
    user: "1000:1000"
    build: .
    restart: always
    ports:
      - "8000:8000"
    networks:
      - drain-network
    volumes:
      - ./db.sqlite3:/app/db.sqlite3
      - ./:/app
      - /var/www/html/nevduplenish:/app/staticgen

networks:
  drain-network:
    name: drain-network