# Generated by Django 5.0.6 on 2024-06-04 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.CharField(default='Нет описания', max_length=128),
        ),
    ]
