# Generated by Django 5.0.6 on 2024-06-08 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_mainbanner_secondarybanner'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(default=None, null=True),
        ),
    ]
