# Generated by Django 5.0.6 on 2024-06-09 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_remove_cartitem_item_cartitem_item_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='default_price',
            field=models.IntegerField(default=1999),
        ),
    ]
