# Generated by Django 4.2.5 on 2024-06-14 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_remove_orderitem_item_orderitem_item_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('CREATED_ORDER', 'Заказ создан'), ('ACCEPTED_ORDER', 'Заказ принят'), ('DELIVERED_ORDER', 'Заказ доставлен'), ('COMPLETED_ORDER', 'Заказ завершен'), ('CANCELLED_ORDER', 'Заказ отменен')], default='CREATED_ORDER', max_length=128),
        ),
    ]
