# Generated by Django 4.2.5 on 2024-06-16 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainbanner',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='secondarybanner',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
