# Generated by Django 4.2.5 on 2024-06-20 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_mainbanner_is_active_secondarybanner_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemsize',
            name='description',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='itemsize',
            name='name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
