# Generated by Django 4.2.5 on 2024-06-01 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20240528_2303'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, 'Заказ создан'), (2, 'Заказ принят'), (3, 'Заказ доставлен'), (4, 'Заказ завершен'), (5, 'Заказ отменен')], default=1)),
            ],
        ),
        migrations.AlterField(
            model_name='itemsize',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
