# Generated by Django 4.2.5 on 2024-06-02 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_statusorder_alter_itemsize_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StatusOrder',
        ),
        migrations.AlterField(
            model_name='orderuser',
            name='status',
            field=models.CharField(choices=[('CREATED_ORDER', 'Заказ создан'), ('ACCEPTED_ORDER', 'Заказ принят'), ('DELIVERED_ORDER', 'Заказ доставлен'), ('COMPLETED_ORDER', 'Заказ завершен'), ('CANCELLED_ORDER', 'Заказ отменен')], default='Заказ создан', max_length=120),
        ),
    ]
