# Generated by Django 4.2.5 on 2024-05-12 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_orderuser_basket_basketitem_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='basketitem',
            name='total',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='basket',
            name='total',
            field=models.IntegerField(default=0),
        ),
    ]
