# Generated by Django 4.2.5 on 2023-11-05 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_item_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='discount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='is_sale',
            field=models.BooleanField(default=False),
        ),
    ]
