# Generated by Django 4.2.5 on 2024-05-16 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_basketitem_total_alter_basket_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderuser',
            name='user',
        ),
        migrations.AddField(
            model_name='orderuser',
            name='basket',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='main.basket'),
        ),
    ]
