# Generated by Django 4.2.5 on 2024-02-01 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_item_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemImg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('imgfield', models.ImageField(upload_to='images/categories/')),
                ('img', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.item')),
            ],
        ),
    ]
