# Generated by Django 4.2.5 on 2024-05-25 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_basket_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'Корзина создана'), (2, 'Пустая'), (3, 'Не звершена'), (4, 'Наполнена'), (5, 'Оплаченная')], default=1),
        ),
        migrations.AddField(
            model_name='orderuser',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'Заказ создан'), (2, 'Заказ принят'), (3, 'Заказ доставлен'), (4, 'Заказ завершен'), (5, 'Заказ отменен')], default=1),
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_datetime', models.DateTimeField(blank=True, null=True)),
                ('status', models.SmallIntegerField(choices=[(1, 'Заказ приянт в обработку'), (2, 'Заказ собран и готов к отправке'), (3, 'Заказ передан курьеру'), (4, 'Заказ находится в пути к месту доставки'), (5, 'Заказ доставлен получателю'), (6, 'Заказ отклонен или отменен'), (7, 'Заказ возвращен на склад'), (8, 'Заказ доставлен, подтверждение получено')], default=1)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.orderuser')),
            ],
        ),
    ]
