# Generated by Django 4.2.5 on 2024-02-01 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_itemimg'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemimg',
            old_name='img',
            new_name='item',
        ),
    ]
