# Generated by Django 4.2.5 on 2024-04-30 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_genderbasictag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gendertag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.genderbasictag'),
        ),
    ]
